name: 'TerrakubeAction'
description: 'Github integration with Terrakube Platform'
branding:
  icon: 'package'  
  color: 'purple'
inputs:
  TERRAKUBE_TOKEN:  
    description: 'Terrakube Personal Access Token'
    required: true
  TERRAKUBE_ENDPOINT:
    description: 'Terrakube Endpoint'
    required: true
  TERRAKUBE_REPOSITORY:
    description: 'Terrakube Repository'
    required: true
  TERRAKUBE_TEMPLATE:
    description: 'Terrakube Template'
    required: true
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
outputs:
  JOB_ID:
    description: 'Terrakube Job Execution Id'
runs:
  using: 'node16'
  main: 'dist/index.js'